### ISSUE TITLE
Error showing Tenant

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#1508]
GUI does not identify user creation with TENANT other than admin.

1°  Creating user by POSTMAN

![Captura de tela de 2020-06-24 08-53-47.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/2ae96662-4080-41b8-8dca-60313c12bffb)

Successfully created.
![Captura de tela de 2020-06-24 12-35-29.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/aa53817e-a89f-49f7-a295-809f0dfbfb76)

2° Accessing LOG auth
![Captura de tela de 2020-06-24 12-24-40.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/54ef35e5-31d7-4a02-8bf4-805114d9db03)

Page inspection
![Captura de tela de 2020-06-24 12-34-20.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/42e3ecae-ca01-4d8c-bdbd-b046da550e1a)

3° Accessing the GUI, TENANT finds himself with the name of USERNAME
![Captura de tela de 2020-06-24 12-25-26.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/355ee4ce-b9fa-4e58-b727-5edfb7a30052)

Tested version: v0.5.0-alpha.1

**Comment by bizetti** [comment]
Ticket analysis: It has to be fixed (0.4.3 and  (0.5.0)

**Comment by betefaber** [comment]
Fixed in basleine v0.4.3-rc.1.

![image](https://user-images.githubusercontent.com/37310063/89938045-4f742d00-dbec-11ea-810d-b28b42de8563.png)

**Comment by betefaber** [comment]
This issue will be tested in v0.5.0.

**Comment by FrancielePessi** [comment]
Error persists in version v0.5.0-alpha.3

![Captura de tela de 2020-08-12 15-40-08](https://user-images.githubusercontent.com/52173618/90054348-21f1b700-dcb2-11ea-9c74-22cfbd6a6566.png)


![Captura de tela de 2020-08-12 15-40-42](https://user-images.githubusercontent.com/52173618/90054416-3766e100-dcb2-11ea-985a-deb58219b27c.png)

**Comment by betefaber** [comment]
Fixed in **v0.5.0-alpha.4**.

![image](https://user-images.githubusercontent.com/37310063/94467351-2eb26780-0199-11eb-9856-915c86bac76c.png)

```
curl -X GET http://${HOST}/auth/user/bete -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json'
{
  "user": {
     "id": "2", 
     "name": "Elisabete", 
     "username": "bete", 
     "service": "teste", 
     "email": "bete@noemail.com", 
     "profile": "admin", 
     "created_date": "2020-09-28 17:39:42.352136", 
     "created_by": "1"
   }
}
```
