### ISSUE TITLE
Error after installation: {"message":"no API found with those values"}

### ISSUE THREAD

**Issue by Lezenunes13** [dojot/dojot#658]
Hi, I've tried to install the dojot platform, following the user guide, but after the installation I got this message 

{"message":"no API found with those values"}

What does it mean?

I started as indicated in the documentation usin the tag 0.1.0-dojot, but I also tried 0.2.0-dojot but the result was the same.

**Comment by giovannicuriel** [comment]
HI!

This means that Kong (our API gateway) was not properly configured. Could you, please, send the state of all containers? You can get this by executing:

```bash
docker-compose ps 
```

**Comment by Lezenunes13** [comment]
Hi @giovannicuriel thanks for your reply. Please take a look athe the information below:

![image](https://user-images.githubusercontent.com/31375287/45587367-fc4baf80-b8da-11e8-9777-c53b2ae6b988.png)

I saw an error during the installation:

![image](https://user-images.githubusercontent.com/31375287/45587387-2f8e3e80-b8db-11e8-8ab5-9f290456059a.png)

Thank you in advance

**Comment by giovannicuriel** [comment]
Hi!

I realized that you are using a quite old version of dojot. Is there any hard requirement to do that?
Also, could you, please send the logs from kong service? You can get it by executing: 

```
docker-compose logs --tail 500 apigw
```

**Comment by Lezenunes13** [comment]
Which version should I use? There is no hard requirement to still at the old one. Tks!

**Comment by giovannicuriel** [comment]
We just released a new one two days ago :tada: (with a quick fix yesterday :grimacing:)
You can get it [here](https://github.com/dojot/docker-compose/releases/tag/v0.3.1). Also, we created a tag for it - if you already have a clone of docker-compose repository, then you could just update your working copy (`git fetch`) and then checkout the newest tag (`git checkout v0.3.1 -b v0.3.1`) and you are good to go.

**Comment by Lezenunes13** [comment]
Hi @giovannicuriel thank you for your reply. I've followed your instructions but still an error. Please take a look: 

![image](https://user-images.githubusercontent.com/31375287/46574411-2ee84580-c979-11e8-8ff3-6d1fdde38caa.png)

What should I do?

**Comment by giovannicuriel** [comment]
There's a good chance that the `docker-compose.yml` file is not in this directory. Could you check that?

**Comment by rascaraficci** [comment]
Closed due to inactivity.
